### ISSUE TITLE
[notify] New service that can consume MQ queues and send emails on certain conditions.

### ISSUE THREAD

**Issue by viklund** [neicnordic/sensitive-data-archive#437]
As a submitter
I want to get notified when something goes wrong with my submission
So that I can investigate it

This is another new service that can notify people in case things happen in the system. It should be configured to be able to listen to queues in the system and upon certain conditions send out an email to the submitter.

## Tasks:
- [x] neicnordic/sda-pipeline#427
- [ ] neicnordic/sda-pipeline#428
- [ ] neicnordic/sda-pipeline#429
