### ISSUE TITLE
[api] As a technical submitter (user), I want an API that I can interact with so that I can control my submission.

### ISSUE THREAD

**Issue by viklund** [neicnordic/sensitive-data-archive#445]
#### Describe the user story
There are several things that an technical person would like to ask the service. These include for example what files are uploaded, how is the submission going, are there any ingestion errors, how many files are left to be ingested. Are all files backed up and so forth.

This issue is a parent issue to a number of other tasks that we need to implement.

#### Tasks:
- [x] neicnordic/sda-pipeline#422
- [ ] neicnordic/sensitive-data-archive#435
- [x] neicnordic/sda-pipeline#424
- [ ] neicnordic/sensitive-data-archive#436

#### Testing 
Unit testing for the API calls. Maybe create a database mock data that has a few files in each state. This can be done   per task above.
